# SPDX-License-Identifier: GPL-2.0

lsdc-y := \
	lsdc_crtc.o \
	lsdc_debugfs.o \
	lsdc_drv.o \
	lsdc_i2c.o \
	lsdc_irq.o \
	lsdc_output.o \
	lsdc_plane.o \
	lsdc_pll.o \
	lsdc_probe.o \
	lsdc_ttm.o

obj-$(CONFIG_DRM_LSDC) += lsdc.o
